import { describe, it, expect, beforeEach, vi } from 'vitest';

/**
 * "Undo this import" must delete exactly the rows that specific import
 * created (never another account's data, never rows from a different
 * import), then fall back to the ordinary snapshot restore for anything the
 * import merely updated in place.
 */

const OWNER = 'owner-1';

const txMock = {
  property: { findMany: vi.fn(() => Promise.resolve([])), upsert: vi.fn(() => Promise.resolve({})) },
  tenant: { findMany: vi.fn(() => Promise.resolve([])), upsert: vi.fn(() => Promise.resolve({})) },
  lease: { findMany: vi.fn(() => Promise.resolve([])), upsert: vi.fn(() => Promise.resolve({})) },
  financialRecord: { findMany: vi.fn(() => Promise.resolve([])), upsert: vi.fn(() => Promise.resolve({})) },
};

const { prismaMock } = vi.hoisted(() => ({
  prismaMock: {
    backup: {
      findFirst: vi.fn(),
      update: vi.fn(() => Promise.resolve({})),
      create: vi.fn(() => Promise.resolve({ id: 'safety-backup', label: '', trigger: 'automated', sizeBytes: 0, createdAt: new Date() })),
    },
    property: { findMany: vi.fn(() => Promise.resolve([])), deleteMany: vi.fn(() => Promise.resolve({ count: 0 })) },
    tenant: { findMany: vi.fn(() => Promise.resolve([])), deleteMany: vi.fn(() => Promise.resolve({ count: 0 })) },
    lease: { findMany: vi.fn(() => Promise.resolve([])), deleteMany: vi.fn(() => Promise.resolve({ count: 0 })) },
    financialRecord: { findMany: vi.fn(() => Promise.resolve([])), deleteMany: vi.fn(() => Promise.resolve({ count: 0 })) },
    $transaction: vi.fn((cb: (tx: unknown) => unknown) => cb(txMock)),
  },
}));

vi.mock('../infrastructure/database', () => ({ prisma: prismaMock }));
vi.mock('../modules/audit/audit.service', () => ({ logAudit: vi.fn() }));

import { attachImportCreatedIds, undoImport } from '../modules/backup/backup.service';

const emptySnapshotData = { properties: [], tenants: [], leases: [], financialRecords: [] };

beforeEach(() => vi.clearAllMocks());

describe('attachImportCreatedIds', () => {
  it('merges the created ids onto the existing snapshot without dropping the original data', async () => {
    prismaMock.backup.findFirst.mockResolvedValueOnce({
      id: 'backup-1', userId: OWNER, snapshot: { version: '1', exportedAt: 'x', data: emptySnapshotData },
    });
    await attachImportCreatedIds('backup-1', OWNER, { properties: ['p1'], tenants: [], leases: ['l1'], financialRecords: [] });
    const patched = prismaMock.backup.update.mock.calls[0][0] as { data: { snapshot: { data: unknown; importedIds: unknown } } };
    expect(patched.data.snapshot.data).toEqual(emptySnapshotData);
    expect(patched.data.snapshot.importedIds).toEqual({ properties: ['p1'], tenants: [], leases: ['l1'], financialRecords: [] });
  });
});

describe('undoImport', () => {
  it('deletes only the rows this import created, scoped to the caller', async () => {
    prismaMock.backup.findFirst.mockResolvedValue({
      id: 'backup-1', userId: OWNER, trigger: 'import',
      snapshot: {
        version: '1', exportedAt: 'x', data: emptySnapshotData,
        importedIds: { properties: ['auto-prop-1'], tenants: ['new-tenant-1'], leases: ['new-lease-1', 'new-lease-2'], financialRecords: [] },
      },
    });

    const result = await undoImport('backup-1', OWNER);

    expect(prismaMock.lease.deleteMany).toHaveBeenCalledWith({
      where: { id: { in: ['new-lease-1', 'new-lease-2'] }, property: { ownerId: OWNER } },
    });
    expect(prismaMock.tenant.deleteMany).toHaveBeenCalledWith({
      where: { id: { in: ['new-tenant-1'] }, ownerId: OWNER },
    });
    expect(prismaMock.property.deleteMany).toHaveBeenCalledWith({
      where: { id: { in: ['auto-prop-1'] }, ownerId: OWNER },
    });
    // Revenue-schedule records generated by the lease import aren't in the
    // tracked id list (they're a side effect), so undo also sweeps by leaseId.
    expect(prismaMock.financialRecord.deleteMany).toHaveBeenCalledWith({
      where: { property: { ownerId: OWNER }, OR: [{ id: { in: [] } }, { leaseId: { in: ['new-lease-1', 'new-lease-2'] } }] },
    });
    expect(result.deleted).toEqual({ properties: 0, tenants: 0, leases: 0, financialRecords: 0 });
  });

  it('deletes children before parents (leases before properties) to respect foreign keys', async () => {
    prismaMock.backup.findFirst.mockResolvedValue({
      id: 'backup-1', userId: OWNER, trigger: 'import',
      snapshot: {
        version: '1', exportedAt: 'x', data: emptySnapshotData,
        importedIds: { properties: ['p1'], tenants: [], leases: ['l1'], financialRecords: [] },
      },
    });
    await undoImport('backup-1', OWNER);
    const leaseOrder = prismaMock.lease.deleteMany.mock.invocationCallOrder[0];
    const propOrder = prismaMock.property.deleteMany.mock.invocationCallOrder[0];
    expect(leaseOrder).toBeLessThan(propOrder);
  });

  it('rejects a backup that was not created by an import', async () => {
    prismaMock.backup.findFirst.mockResolvedValue({
      id: 'backup-1', userId: OWNER, trigger: 'manual', snapshot: { version: '1', exportedAt: 'x', data: emptySnapshotData },
    });
    await expect(undoImport('backup-1', OWNER)).rejects.toThrow(/not created by an import/i);
  });

  it('rejects an import backup that predates undo support (no importedIds)', async () => {
    prismaMock.backup.findFirst.mockResolvedValue({
      id: 'backup-1', userId: OWNER, trigger: 'import', snapshot: { version: '1', exportedAt: 'x', data: emptySnapshotData },
    });
    await expect(undoImport('backup-1', OWNER)).rejects.toThrow(/predates undo support/i);
  });

  it('never deletes across accounts even if the backup somehow held a foreign id', async () => {
    prismaMock.backup.findFirst.mockResolvedValue({
      id: 'backup-1', userId: OWNER, trigger: 'import',
      snapshot: {
        version: '1', exportedAt: 'x', data: emptySnapshotData,
        importedIds: { properties: ['someone-elses-property'], tenants: [], leases: [], financialRecords: [] },
      },
    });
    await undoImport('backup-1', OWNER);
    expect(prismaMock.property.deleteMany).toHaveBeenCalledWith({
      where: { id: { in: ['someone-elses-property'] }, ownerId: OWNER },
    });
  });
});
